import { ViewType } from '@/features/income-management/types/view-types.ts';
/**
 * @file dummy.ts
 * @description
 * Centralized dummy data map for all ViewTypes in the MWSS Income/Raw Water Management app.
 *
 * @usage
 * - Import `dummyDataMap` and use it in hooks or components for local development/testing.
 * - Each key matches a ViewType and provides an array of dummy objects for that view.
 *
 * @example
 * import dummyDataMap from '@/features/income-management/utils/dummy';
 * const data = dummyDataMap[viewType];
 *
 * @see
 * Add or update dummy data here for any new or existing view type.
 * Keep each array concise (e.g., 5 entries) for fast UI testing.
 */
const dummyDataMap: Record<ViewType, any[]> = {
  'billing-statement': [
    {
      date: '2024-06-01',
      controlNumber: 'BS-001',
      lessee: 'John Doe',
      companyName: 'Acme Corp',
      subject: 'Monthly Rent',
      dateReceived: '2024-06-02',
      status: 'For Review [1/4]',
      remarks: 'Payment pending',
    },
    {
      date: '2024-06-02',
      controlNumber: 'BS-002',
      lessee: 'Jane Smith',
      companyName: 'Beta LLC',
      subject: 'Water Bill',
      dateReceived: '2024-06-03',
      status: 'Approved',
      remarks: '',
    },
    {
      date: '2024-06-03',
      controlNumber: 'BS-003',
      lessee: 'Alice Johnson',
      companyName: 'Gamma Inc',
      subject: 'Maintenance Fee',
      dateReceived: '2024-06-04',
      status: 'Returned',
      remarks: 'Incorrect amount',
    },
    {
      date: '2024-06-04',
      controlNumber: 'BS-004',
      lessee: 'Bob Lee',
      companyName: 'Delta Ltd',
      subject: 'Electricity Bill',
      dateReceived: '2024-06-05',
      status: 'For Review [2/4]',
      remarks: '',
    },
    {
      date: '2024-06-05',
      controlNumber: 'BS-005',
      lessee: 'Carol King',
      companyName: 'Epsilon Co',
      subject: 'Monthly Rent',
      dateReceived: '2024-06-06',
      status: 'Approved',
      remarks: 'Paid early',
    },
    {
      date: '2024-06-06',
      controlNumber: 'BS-006',
      lessee: 'David Kim',
      companyName: 'Zeta Group',
      subject: 'Water Bill',
      dateReceived: '2024-06-07',
      status: 'Returned',
      remarks: 'Missing signature',
    },
    {
      date: '2024-06-07',
      controlNumber: 'BS-007',
      lessee: 'Eva Green',
      companyName: 'Eta Solutions',
      subject: 'Maintenance Fee',
      dateReceived: '2024-06-08',
      status: 'Approved',
      remarks: '',
    },
    {
      date: '2024-06-08',
      controlNumber: 'BS-008',
      lessee: 'Frank Moore',
      companyName: 'Theta Services',
      subject: 'Electricity Bill',
      dateReceived: '2024-06-09',
      status: 'For Review',
      remarks: '',
    },
    {
      date: '2024-06-09',
      controlNumber: 'BS-009',
      lessee: 'Grace Lee',
      companyName: 'Iota Holdings',
      subject: 'Monthly Rent',
      dateReceived: '2024-06-10',
      status: 'Returned',
      remarks: 'Document incomplete',
    },
    {
      date: '2024-06-10',
      controlNumber: 'BS-010',
      lessee: 'Henry Ford',
      companyName: 'Kappa Ventures',
      subject: 'Water Bill',
      dateReceived: '2024-06-11',
      status: 'Approved',
      remarks: '',
    },
    {
      date: '2024-06-11',
      controlNumber: 'BS-011',
      lessee: 'Ivy Chan',
      companyName: 'Lambda Partners',
      subject: 'Maintenance Fee',
      dateReceived: '2024-06-12',
      status: 'For Review',
      remarks: '',
    },
    {
      date: '2024-06-12',
      controlNumber: 'BS-012',
      lessee: 'Jack Black',
      companyName: 'Mu Technologies',
      subject: 'Electricity Bill',
      dateReceived: '2024-06-13',
      status: 'Approved',
      remarks: '',
    },
    {
      date: '2024-06-13',
      controlNumber: 'BS-013',
      lessee: 'Karen White',
      companyName: 'Nu Enterprises',
      subject: 'Monthly Rent',
      dateReceived: '2024-06-14',
      status: 'Returned',
      remarks: 'Late submission',
    },
    {
      date: '2024-06-14',
      controlNumber: 'BS-014',
      lessee: 'Leo Brown',
      companyName: 'Xi Logistics',
      subject: 'Water Bill',
      dateReceived: '2024-06-15',
      status: 'Approved',
      remarks: '',
    },
    {
      date: '2024-06-15',
      controlNumber: 'BS-015',
      lessee: 'Mona Lisa',
      companyName: 'Omicron Foods',
      subject: 'Maintenance Fee',
      dateReceived: '2024-06-16',
      status: 'For Review',
      remarks: '',
    },
  ],
  'statement-of-account': [
    {
      date: '2024-06-01',
      controlNumber: 'SOA-001',
      lessee: 'SOA-1',
      companyName: 'Acme Corp',
      subject: 'Monthly Rent',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'For Review',
      remarks: 'Payment received on time',
    },
    {
      date: '2024-06-02',
      controlNumber: 'SOA-002',
      lessee: 'SOA-2',
      companyName: 'Beta LLC',
      subject: 'Water Bill',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'Approved',
      remarks: 'Pending payment',
    },
    {
      date: '2024-06-03',
      controlNumber: 'SOA-003',
      lessee: 'SOA-3',
      companyName: 'Gamma Inc',
      subject: 'Maintenance Fee',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'For Review',
      remarks: 'Partial payment received',
    },
    {
      date: '2024-06-04',
      controlNumber: 'SOA-004',
      lessee: 'SOA-4',
      companyName: 'Delta Ltd',
      subject: 'Electricity Bill',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'For Review',
      remarks: 'Overdue by 5 days',
    },
    {
      date: '2024-06-05',
      controlNumber: 'SOA-005',
      lessee: 'SOA-5',
      companyName: 'Epsilon Co',
      subject: 'Monthly Rent',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'Returned',
      remarks: '',
    },
    {
      date: '2024-06-06',
      controlNumber: 'SOA-006',
      lessee: 'SOA-6',
      companyName: 'Zeta Group',
      subject: 'Water Bill',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'Approved',
      remarks: 'Awaiting confirmation',
    },
    {
      date: '2024-06-07',
      controlNumber: 'SOA-007',
      lessee: 'SOA-7',
      companyName: 'Eta Solutions',
      subject: 'Maintenance Fee',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'Returned',
      remarks: 'Paid via bank transfer',
    },
    {
      date: '2024-06-08',
      controlNumber: 'SOA-008',
      lessee: 'SOA-8',
      companyName: 'Theta Services',
      subject: 'Electricity Bill',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'Approved',
      remarks: '',
    },
    {
      date: '2024-06-09',
      controlNumber: 'SOA-009',
      lessee: 'SOA-9',
      companyName: 'Iota Holdings',
      subject: 'Monthly Rent',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'Returned',
      remarks: '',
    },
    {
      date: '2024-06-10',
      controlNumber: 'SOA-010',
      lessee: 'SOA-10',
      companyName: 'Kappa Ventures',
      subject: 'Water Bill',
      periodCovered: '2024-06-01 to 2024-06-30',
      status: 'Returned',
      remarks: 'Reminder sent',
    },
  ],
  'demand-to-pay': [
    {
      status: 'approved',
      date: '2025-06-01',
      controlNumber: 'CN-001',
      lessee: 'Juan Dela Cruz',
      companyName: 'Alpha Corp',
      subject: 'Lease Renewal',
      dateReceived: '2025-05-28',
    },
    {
      status: 'for review[1/4]',
      date: '2025-06-02',
      controlNumber: 'CN-002',
      lessee: 'Maria Santos',
      companyName: 'Beta Ltd',
      subject: 'Lease Termination',
      dateReceived: '2025-05-30',
    },
    {
      status: 'settled [1/3]',
      date: '2025-05-30',
      controlNumber: 'CN-003',
      lessee: 'Pedro Gomez',
      companyName: 'Gamma Ventures',
      subject: 'Payment Settlement',
      dateReceived: '2025-05-29',
    },
    {
      status: 'returned',
      date: '2025-05-25',
      controlNumber: 'CN-004',
      lessee: 'Carla Ramos',
      companyName: 'Delta Corp',
      subject: 'Document Review',
      dateReceived: '2025-05-23',
    },
    {
      status: 'rejected',
      date: '2025-05-20',
      controlNumber: 'CN-005',
      lessee: 'Luis Enriquez',
      companyName: 'Epsilon Inc',
      subject: 'Late Submission',
      dateReceived: '2025-05-19',
    },
    {
      status: 'settled [2/4]',
      date: '2025-05-15',
      controlNumber: 'CN-006',
      lessee: 'Grace Villanueva',
      companyName: 'Zeta Tech',
      subject: 'Installment Payment',
      dateReceived: '2025-05-14',
    },
    {
      status: 'unpaid',
      date: '2025-05-10',
      controlNumber: 'CN-007',
      lessee: 'Danilo Cruz',
      companyName: 'Theta Holdings',
      subject: 'Outstanding Invoice',
      dateReceived: '2025-05-09',
    },
    {
      status: 'completed',
      date: '2025-05-05',
      controlNumber: 'CN-008',
      lessee: 'Elaine Lopez',
      companyName: 'Iota Services',
      subject: 'Contract Completion',
      dateReceived: '2025-05-03',
    },
    {
      status: 'overdue',
      date: '2025-04-30',
      controlNumber: 'CN-009',
      lessee: 'Oscar Mendoza',
      companyName: 'Kappa Build',
      subject: 'Overdue Rent',
      dateReceived: '2025-04-28',
    },
    {
      status: 'settled [3/3]',
      date: '2025-04-25',
      controlNumber: 'CN-010',
      lessee: 'Isabel Navarro',
      companyName: 'Lambda Co.',
      subject: 'Final Payment',
      dateReceived: '2025-04-24',
    },
  ],
  'payment-monitoring': [
    { transactionId: 'TX-001', paymentDate: '2025-05-01' },
    { transactionId: 'TX-002', paymentDate: '2025-05-02' },
  ],
  'payment-reconciliation': [
    {
      transactionId: 'PR-001',
      controlNumber: 'BS-001',
      lessee: 'John Doe',
      companyName: 'Acme Corp',
      paymentDate: '2024-06-01',
      amountPaid: 12000,
      paymentMethod: 'Bank Transfer',
      status: 'Reconciled',
    },
    {
      transactionId: 'PR-002',
      controlNumber: 'BS-002',
      lessee: 'Jane Smith',
      companyName: 'Beta LLC',
      paymentDate: '2024-06-02',
      amountPaid: 2500,
      paymentMethod: 'Check',
      status: 'Pending Verification',
    },
    {
      transactionId: 'PR-003',
      controlNumber: 'BS-003',
      lessee: 'Alice Johnson',
      companyName: 'Gamma Inc',
      paymentDate: '2024-06-03',
      amountPaid: 3400,
      paymentMethod: 'Cash',
      status: 'Reconciled',
    },
  ],
  'payment-history': [
    {
      soaControlNumber: 'SOA-001',
      soaAmount: 12000,
      orDate: '2024-05-30',
      lessee: 'John Doe',
      orNo: 'OR-001',
      paymentMade: 12000,
      balanceDue: 0,
    },
    {
      soaControlNumber: 'SOA-002',
      soaAmount: 2500,
      orDate: '2024-05-31',
      lessee: 'Jane Smith',
      orNo: 'OR-002',
      paymentMade: 2500,
      balanceDue: 0,
    },
    {
      soaControlNumber: 'SOA-003',
      soaAmount: 3400,
      orDate: '2024-06-01',
      lessee: 'Alice Johnson',
      orNo: 'OR-003',
      paymentMade: 2400,
      balanceDue: 1000,
    },
    {
      soaControlNumber: 'SOA-004',
      soaAmount: 3000,
      orDate: '2024-06-01',
      lessee: 'Alice Johnson',
      orNo: 'OR-004',
      paymentMade: 1000,
      balanceDue: 2000,
    },
  ],
  'payment-reminder': [
    {
      lessee: 'John Doe',
      noticeCount: 2,
      demandDate: '2024-06-10',
      controlNumber: 'DTP-001',
      amount: 12000,
      remarks: 'Pending payment, last notice sent 2024-06-01',
    },
    {
      lessee: 'Jane Smith',
      noticeCount: 1,
      demandDate: '2024-06-12',
      controlNumber: 'DTP-002',
      amount: 2500,
      remarks: 'Paid on 2024-06-05',
    },
    {
      lessee: 'Alice Johnson',
      noticeCount: 3,
      demandDate: '2024-06-15',
      controlNumber: 'DTP-003',
      amount: 3400,
      remarks: 'Unpaid, last reminder sent 2024-06-05',
    },
  ],
  

  'journal-entry': [
    {
      jevDate: '2025-06-02',
      jevNo: 'JEV-002',
      accountTitle: 'Accounts Payable',
      particulars: 'Correction of invoice error',
      debit: 0,
      credit: 300,
    },
    {
      jevDate: '2025-06-03',
      jevNo: 'JEV-003',
      accountTitle: 'Office Supplies',
      particulars: 'Purchase of supplies',
      debit: 200,
      credit: 0,
    },
    {
      jevDate: '2025-06-03',
      jevNo: 'JEV-004',
      accountTitle: 'Cash in Bank',
      particulars: 'Payment for office supplies',
      debit: 0,
      credit: 200,
    },
    {
      jevDate: '2025-06-04',
      jevNo: 'JEV-005',
      accountTitle: 'Salaries Expense',
      particulars: 'Salary payment for June',
      debit: 1000,
      credit: 0,
    },
  ],

  'invoice-tracking': [
    {
      lessee: 'Acme Corp.',
      invoiceDate: '2025-06-01',
      invoiceNo: 'INV-001',
      amount: 1000,
      status: 'Paid',
    },
    {
      lessee: 'Beta Solutions',
      invoiceDate: '2025-06-02',
      invoiceNo: 'INV-002',
      amount: 2500,
      status: 'Pending',
    },
    {
      lessee: 'Cyber Systems',
      invoiceDate: '2025-06-03',
      invoiceNo: 'INV-003',
      amount: 1850,
      status: 'Overdue',
    },
    {
      lessee: 'Delta Logistics',
      invoiceDate: '2025-06-04',
      invoiceNo: 'INV-004',
      amount: 3200,
      status: 'Paid',
    },
    {
      lessee: 'Eco Rentals',
      invoiceDate: '2025-06-05',
      invoiceNo: 'INV-005',
      amount: 1450,
      status: 'Cancelled',
    },
    {
      lessee: 'FastTrack Inc.',
      invoiceDate: '2025-06-06',
      invoiceNo: 'INV-006',
      amount: 2750,
      status: 'Pending',
    },
  ],

  'lessee-information': [
    {
      status: 'Active',
      lesseeNo: 'LES-001',
      nameOfLessee: 'Juan Dela Cruz',
      location: 'Unit 101-A',
      lesseeTerm: 'Jan 2024 - Dec 2024',
      classification: 'Retail',
      remarks: 'On time',
    },
    {
      status: 'Expired',
      lesseeNo: 'LES-002',
      nameOfLessee: 'Maria Santos',
      location: 'Unit 102-B',
      lesseeTerm: 'Feb 2023 - Jan 2024',
      classification: 'Food',
      remarks: 'Contract ended',
    },
    {
      status: 'Active',
      lesseeNo: 'LES-003',
      nameOfLessee: 'Jose Rizal',
      location: 'Unit 103-C',
      lesseeTerm: 'Mar 2024 - Feb 2025',
      classification: 'Service',
      remarks: 'New tenant',
    },
    {
      status: 'Expired',
      lesseeNo: 'LES-004',
      nameOfLessee: 'Andres Bonifacio',
      location: 'Unit 104-D',
      lesseeTerm: 'Apr 2024 - Mar 2025',
      classification: 'Retail',
      remarks: 'For approval',
    },
    {
      status: 'Active',
      lesseeNo: 'LES-005',
      nameOfLessee: 'Gregoria de Jesus',
      location: 'Unit 105-E',
      lesseeTerm: 'May 2024 - Apr 2025',
      classification: 'Food',
      remarks: 'Renewed',
    },
    {
      status: 'Expired',
      lesseeNo: 'LES-006',
      nameOfLessee: 'Emilio Aguinaldo',
      location: 'Unit 106-F',
      lesseeTerm: 'Jun 2023 - May 2024',
      classification: 'Office',
      remarks: 'Moved out',
    },
  ],
  'raw-water-billing-statement': [
    {
      invoiceDate: '2024-06-01',
      invoiceNo: 'RWBS-001',
      customerName: 'ABC Waterworks',
      companyName: 'Acme Water Inc.',
      subject: 'Raw Water Billing for June',
      periodCovered: '2024-06-01 to 2024-06-30',
      remarks: 'Paid on time',
    },
    {
      invoiceDate: '2024-06-05',
      invoiceNo: 'RWBS-002',
      customerName: 'DEF Hydration',
      companyName: 'Delta H2O Corp.',
      subject: 'Raw Water Billing for June',
      periodCovered: '2024-06-01 to 2024-06-30',
      remarks: 'Pending payment',
    },
    {
      invoiceDate: '2024-06-10',
      invoiceNo: 'RWBS-003',
      customerName: 'GHI Springs',
      companyName: 'Gamma Aqua Ltd.',
      subject: 'Raw Water Billing for June',
      periodCovered: '2024-06-01 to 2024-06-30',
      remarks: '',
    },
    {
      invoiceDate: '2024-06-15',
      invoiceNo: 'RWBS-004',
      customerName: 'JKL Purified',
      companyName: 'Jade Water Solutions',
      subject: 'Raw Water Billing for June',
      periodCovered: '2024-06-01 to 2024-06-30',
      remarks: 'Partial payment',
    },
    {
      invoiceDate: '2024-06-20',
      invoiceNo: 'RWBS-005',
      customerName: 'MNO Aquatics',
      companyName: 'Omega Water Corp.',
      subject: 'Raw Water Billing for June',
      periodCovered: '2024-06-01 to 2024-06-30',
      remarks: '',
    },
  ],

  'raw-water-demand-to-pay': [
    {
      date: '2024-06-02',
      controlNumber: 'RWDTP-001',
      customerName: 'ABC Waterworks',
      companyName: 'Acme Water Inc.',
      subject: 'Demand for Payment',
      dateReceived: '2024-06-03',
      status: 'For Review',
      remarks: 'Urgent',
    },
    {
      date: '2024-06-07',
      controlNumber: 'RWDTP-002',
      customerName: 'DEF Hydration',
      companyName: 'Delta H2O Corp.',
      subject: 'Demand for Payment',
      dateReceived: '2024-06-08',
      status: 'Approved',
      remarks: '',
    },
    {
      date: '2024-06-12',
      controlNumber: 'RWDTP-003',
      customerName: 'GHI Springs',
      companyName: 'Gamma Aqua Ltd.',
      subject: 'Demand for Payment',
      dateReceived: '2024-06-13',
      status: 'Returned',
      remarks: 'Incorrect details',
    },
    {
      date: '2024-06-17',
      controlNumber: 'RWDTP-004',
      customerName: 'JKL Purified',
      companyName: 'Jade Water Solutions',
      subject: 'Demand for Payment',
      dateReceived: '2024-06-18',
      status: 'For Review',
      remarks: '',
    },
    {
      date: '2024-06-22',
      controlNumber: 'RWDTP-005',
      customerName: 'MNO Aquatics',
      companyName: 'Omega Water Corp.',
      subject: 'Demand for Payment',
      dateReceived: '2024-06-23',
      status: 'Approved',
      remarks: '',
    },
  ],

  'raw-water-journal-entry': [
    {
      jevDate: '2024-06-04',
      jevNo: 'RWJEV-001',
      accountTitle: 'Raw Water Revenue',
      particulars: 'June 2024 Billing',
      debit: 10000,
      credit: 10000,
    },
    {
      jevDate: '2024-06-09',
      jevNo: 'RWJEV-002',
      accountTitle: 'Accounts Receivable',
      particulars: 'Payment Received',
      debit: 8000,
      credit: 8000,
    },
    {
      jevDate: '2024-06-14',
      jevNo: 'RWJEV-003',
      accountTitle: 'Other Income',
      particulars: 'Late Fee',
      debit: 500,
      credit: 500,
    },
    {
      jevDate: '2024-06-19',
      jevNo: 'RWJEV-004',
      accountTitle: 'Raw Water Revenue',
      particulars: 'Adjustment',
      debit: 200,
      credit: 200,
    },
    {
      jevDate: '2024-06-24',
      jevNo: 'RWJEV-005',
      accountTitle: 'Accounts Receivable',
      particulars: 'Reversal',
      debit: 1000,
      credit: 1000,
    },
  ],

  'raw-water-invoice-tracking': [
    {
      lesseeName: 'ABC Waterworks',
      invoiceDate: '2024-06-01',
      invoiceNo: 'RWINV-001',
      amount: 5000,
      status: 'Paid',
    },
    {
      lesseeName: 'DEF Hydration',
      invoiceDate: '2024-06-05',
      invoiceNo: 'RWINV-002',
      amount: 7000,
      status: 'Pending',
    },
    {
      lesseeName: 'GHI Springs',
      invoiceDate: '2024-06-10',
      invoiceNo: 'RWINV-003',
      amount: 6000,
      status: 'Paid',
    },
    {
      lesseeName: 'JKL Purified',
      invoiceDate: '2024-06-15',
      invoiceNo: 'RWINV-004',
      amount: 8000,
      status: 'Overdue',
    },
    {
      lesseeName: 'MNO Aquatics',
      invoiceDate: '2024-06-20',
      invoiceNo: 'RWINV-005',
      amount: 9000,
      status: 'Paid',
    },
  ],

  'raw-water-invoice-list': [
    {
      lesseeName: 'ABC Waterworks',
      invoiceDate: '2024-06-01',
      invoiceNo: 'RWLIST-001',
      amount: 5000,
      status: 'Paid',
    },
    {
      lesseeName: 'DEF Hydration',
      invoiceDate: '2024-06-05',
      invoiceNo: 'RWLIST-002',
      amount: 7000,
      status: 'Pending',
    },
    {
      lesseeName: 'GHI Springs',
      invoiceDate: '2024-06-10',
      invoiceNo: 'RWLIST-003',
      amount: 6000,
      status: 'Paid',
    },
    {
      lesseeName: 'JKL Purified',
      invoiceDate: '2024-06-15',
      invoiceNo: 'RWLIST-004',
      amount: 8000,
      status: 'Overdue',
    },
    {
      lesseeName: 'MNO Aquatics',
      invoiceDate: '2024-06-20',
      invoiceNo: 'RWLIST-005',
      amount: 9000,
      status: 'Paid',
    },
  ],

  'raw-water-customer-invoice-reports': [
    {
      lesseeName: 'ABC Waterworks',
      billingDate: '2024-06-01',
      billingControlNo: 'RWCIR-001',
      billingControlNo2: 'RWCIR2-001',
      modeOfPayment: 'Cash',
      referenceOrCheck: 'CHK-001',
    },
    {
      lesseeName: 'DEF Hydration',
      billingDate: '2024-06-05',
      billingControlNo: 'RWCIR-002',
      billingControlNo2: 'RWCIR2-002',
      modeOfPayment: 'Check',
      referenceOrCheck: 'CHK-002',
    },
    {
      lesseeName: 'GHI Springs',
      billingDate: '2024-06-10',
      billingControlNo: 'RWCIR-003',
      billingControlNo2: 'RWCIR2-003',
      modeOfPayment: 'Bank Transfer',
      referenceOrCheck: 'BT-003',
    },
    {
      lesseeName: 'JKL Purified',
      billingDate: '2024-06-15',
      billingControlNo: 'RWCIR-004',
      billingControlNo2: 'RWCIR2-004',
      modeOfPayment: 'Cash',
      referenceOrCheck: 'CHK-004',
    },
    {
      lesseeName: 'MNO Aquatics',
      billingDate: '2024-06-20',
      billingControlNo: 'RWCIR-005',
      billingControlNo2: 'RWCIR2-005',
      modeOfPayment: 'Check',
      referenceOrCheck: 'CHK-005',
    },
  ],

  'raw-water-customer-information-management': [
    {
      customerNo: 'RWCI-001',
      customerName: 'ABC Waterworks',
      address: '123 Main St',
      contractExecution: '2024-01-01',
      classification: 'Commercial',
      status: 'Active',
    },
    {
      customerNo: 'RWCI-002',
      customerName: 'DEF Hydration',
      address: '456 Elm St',
      contractExecution: '2024-02-01',
      classification: 'Industrial',
      status: 'Inactive',
    },
    {
      customerNo: 'RWCI-003',
      customerName: 'GHI Springs',
      address: '789 Oak St',
      contractExecution: '2024-03-01',
      classification: 'Commercial',
      status: 'Active',
    },
    {
      customerNo: 'RWCI-004',
      customerName: 'JKL Purified',
      address: '101 Pine St',
      contractExecution: '2024-04-01',
      classification: 'Industrial',
      status: 'Inactive',
    },
    {
      customerNo: 'RWCI-005',
      customerName: 'MNO Aquatics',
      address: '202 Maple St',
      contractExecution: '2024-05-01',
      classification: 'Commercial',
      status: 'Active',
    },
  ],

  'raw-water-customer-information': [
    {
      customerNo: 'RWCI-001',
      customerName: 'ABC Waterworks',
      address: '123 Main St',
      contractExecution: '2024-01-01',
      classification: 'Commercial',
      status: 'Active',
    },
    {
      customerNo: 'RWCI-002',
      customerName: 'DEF Hydration',
      address: '456 Elm St',
      contractExecution: '2024-02-01',
      classification: 'Industrial',
      status: 'Inactive',
    },
    {
      customerNo: 'RWCI-003',
      customerName: 'GHI Springs',
      address: '789 Oak St',
      contractExecution: '2024-03-01',
      classification: 'Commercial',
      status: 'Active',
    },
    {
      customerNo: 'RWCI-004',
      customerName: 'JKL Purified',
      address: '101 Pine St',
      contractExecution: '2024-04-01',
      classification: 'Industrial',
      status: 'Inactive',
    },
    {
      customerNo: 'RWCI-005',
      customerName: 'MNO Aquatics',
      address: '202 Maple St',
      contractExecution: '2024-05-01',
      classification: 'Commercial',
      status: 'Active',
    },
  ],

  'raw-water-customer-payment-history': [
    {
      date: '2024-06-01',
      soaNo: 'RWCPH-001',
      amount: 5000,
      status: 'Paid',
    },
    {
      date: '2024-06-05',
      soaNo: 'RWCPH-002',
      amount: 7000,
      status: 'Pending',
    },
    {
      date: '2024-06-10',
      soaNo: 'RWCPH-003',
      amount: 6000,
      status: 'Paid',
    },
    {
      date: '2024-06-15',
      soaNo: 'RWCPH-004',
      amount: 8000,
      status: 'Overdue',
    },
    {
      date: '2024-06-20',
      soaNo: 'RWCPH-005',
      amount: 9000,
      status: 'Paid',
    },
  ],

  'raw-water-payment-monitoring': [
    {
      date: '2024-06-01',
      soaNo: 'RWPM-001',
      amount: 5000,
      status: 'Paid',
    },
    {
      date: '2024-06-05',
      soaNo: 'RWPM-002',
      amount: 7000,
      status: 'Pending',
    },
    {
      date: '2024-06-10',
      soaNo: 'RWPM-003',
      amount: 6000,
      status: 'Paid',
    },
    {
      date: '2024-06-15',
      soaNo: 'RWPM-004',
      amount: 8000,
      status: 'Overdue',
    },
    {
      date: '2024-06-20',
      soaNo: 'RWPM-005',
      amount: 9000,
      status: 'Paid',
    },
  ],

  'raw-water-payment-reconciliation': [
    {
      lesseeName: 'ABC Waterworks',
      soaControlNo: 'RWPR-001',
      soaAmount: 5000,
      orDate: '2024-06-01',
      orNo: 'OR-001',
      paymentAmount: 5000,
      balanceDue: 0,
    },
    {
      lesseeName: 'DEF Hydration',
      soaControlNo: 'RWPR-002',
      soaAmount: 7000,
      orDate: '2024-06-05',
      orNo: 'OR-002',
      paymentAmount: 7000,
      balanceDue: 0,
    },
    {
      lesseeName: 'GHI Springs',
      soaControlNo: 'RWPR-003',
      soaAmount: 6000,
      orDate: '2024-06-10',
      orNo: 'OR-003',
      paymentAmount: 6000,
      balanceDue: 0,
    },
    {
      lesseeName: 'JKL Purified',
      soaControlNo: 'RWPR-004',
      soaAmount: 8000,
      orDate: '2024-06-15',
      orNo: 'OR-004',
      paymentAmount: 8000,
      balanceDue: 0,
    },
    {
      lesseeName: 'MNO Aquatics',
      soaControlNo: 'RWPR-005',
      soaAmount: 9000,
      orDate: '2024-06-20',
      orNo: 'OR-005',
      paymentAmount: 9000,
      balanceDue: 0,
    },
  ],

  'raw-water-payment-history': [
    {
      lesseeName: 'ABC Waterworks',
      soaControlNo: 'RWPH-001',
      soaAmount: 5000,
      orDate: '2024-06-01',
      orNo: 'OR-001',
      paymentAmount: 5000,
      balanceDue: 0,
    },
    {
      lesseeName: 'DEF Hydration',
      soaControlNo: 'RWPH-002',
      soaAmount: 7000,
      orDate: '2024-06-05',
      orNo: 'OR-002',
      paymentAmount: 7000,
      balanceDue: 0,
    },
    {
      lesseeName: 'GHI Springs',
      soaControlNo: 'RWPH-003',
      soaAmount: 6000,
      orDate: '2024-06-10',
      orNo: 'OR-003',
      paymentAmount: 6000,
      balanceDue: 0,
    },
    {
      lesseeName: 'JKL Purified',
      soaControlNo: 'RWPH-004',
      soaAmount: 8000,
      orDate: '2024-06-15',
      orNo: 'OR-004',
      paymentAmount: 8000,
      balanceDue: 0,
    },
    {
      lesseeName: 'MNO Aquatics',
      soaControlNo: 'RWPH-005',
      soaAmount: 9000,
      orDate: '2024-06-20',
      orNo: 'OR-005',
      paymentAmount: 9000,
      balanceDue: 0,
    },
  ],

  'raw-water-payment-reminder': [
    {
      lesseeName: 'ABC Waterworks',
      noticeCount: 1,
      demandDate: '2024-06-01',
      demandControlNo: 'RWPR-001',
      amount: 5000,
      remarks: 'First notice',
    },
    {
      lesseeName: 'DEF Hydration',
      noticeCount: 2,
      demandDate: '2024-06-05',
      demandControlNo: 'RWPR-002',
      amount: 7000,
      remarks: 'Second notice',
    },
    {
      lesseeName: 'GHI Springs',
      noticeCount: 1,
      demandDate: '2024-06-10',
      demandControlNo: 'RWPR-003',
      amount: 6000,
      remarks: 'First notice',
    },
    {
      lesseeName: 'JKL Purified',
      noticeCount: 3,
      demandDate: '2024-06-15',
      demandControlNo: 'RWPR-004',
      amount: 8000,
      remarks: 'Third notice',
    },
    {
      lesseeName: 'MNO Aquatics',
      noticeCount: 2,
      demandDate: '2024-06-20',
      demandControlNo: 'RWPR-005',
      amount: 9000,
      remarks: 'Second notice',
    },
  ],

  'raw-water-payment-computation': [],
  'raw-water-payment-computation-cpi': [
    {
      period: '2024-01',
      index2006: 120.5,
      index2012: 110.2,
      index2018: 105.3,
      percentIndex: 2.5,
    },
    {
      period: '2024-02',
      index2006: 121.0,
      index2012: 110.8,
      index2018: 105.7,
      percentIndex: 2.7,
    },
    {
      period: '2024-03',
      index2006: 121.3,
      index2012: 111.1,
      index2018: 106.0,
      percentIndex: 2.8,
    },
    {
      period: '2024-04',
      index2006: 121.7,
      index2012: 111.5,
      index2018: 106.4,
      percentIndex: 2.9,
    },
    {
      period: '2024-05',
      index2006: 122.0,
      index2012: 111.8,
      index2018: 106.7,
      percentIndex: 3.0,
    },
  ],

  'raw-water-payment-computation-arrears': [],
  'raw-water-dashboard': [],
  'concession-fee': [],
};

export default dummyDataMap;
